### ISSUE TITLE
FHEM Modul fehlt

### ISSUE THREAD

**Issue by Dud3z** [yanniks/ghome-fhem#1]
Hi,

erstmal VIELEN DANK für die Arbeit die Du Dir machst ;-)

Ich habe mich heute mal dran versucht bin aber an einem fehlenden Device mit dem TYPE ghome gescheitert. Kann es sein das wir hier ein FHEM Modul benötigen?

**Comment by Simple-codinger** [comment]
Ich habe kein FHEM Modul benötigt. Existiert der Fehler noch? Kannst du mal deinen Output posten?

**Comment by yanniks** [comment]
Hi ihr beiden,
erstmal Danke an @Simple-codinger, dass du dich hier in Support versuchst :)
In der Tat gibt es für das Alexa-Projekt ein passendes FHEM-Device, was hier auch noch irgendwo im Code drin steckt. Ohne geht es aber auch, denn ein solches Device existiert nicht. Das wäre aber bestimmt ein Verbesserungsvorschlag, das mal zu entfernen. ;)
Jetzt wo ich wieder etwas Luft habe, kümmere ich mich die Tage dann auch mal um das FHEM-Forum.

Viele Grüße
Yannik

**Comment by Dud3z** [comment]
Hat sich erledigt.... das Script hat es immer angemeckert... das ist alles. es hat an einer anderen Stelle nicht funktioniert. Dafür war aber ich verantwortlich. Issue somit nicht relevant ;-)
