### ISSUE TITLE
Thermostats without currentTemperature not working

### ISSUE THREAD

**Issue by dominikkarall** [yanniks/ghome-fhem#2]
Hi,
it would be great if you could change the procedure how a thermostat is identified. EQ3BT thermostats don't have a CurrentTemperature value and therefore don't work as long as no mapping is created. My recommendation is to change the if statement below to DesiredTemperature. I'm not sure if it would still work without CurrentTemperature mapping, if not, a workaround would be to set CurrentTemperature to DesiredTemperature.

https://github.com/yanniks/ghome-fhem/blob/d440420e21197d2f531de7a632ae2aebac21e05e/lib/server.js#L1641

Thanks,
Dominik

**Comment by yanniks** [comment]
Well, it could check if CurrentTemperature or DesiredTemperature is set, one should be enough. Will push a change in a minute :)
