### ISSUE TITLE
EXECUTE not working properly any more (solution provided)

### ISSUE THREAD

**Issue by dominikkarall** [yanniks/ghome-fhem#4]
Hi,

could you please add following lines
```
    });

    let res = {commands: responses};

    return res;

}; // handleControl
```

here...
https://github.com/yanniks/ghome-fhem/blob/0c9bb9d75fab847476428e37f3b03c134bb48087/lib/server.js#L1627

Thanks, that solves the current error message when executing commands to devices.

Regards
Dominik

**Comment by yanniks** [comment]
Hi Dominik,
thanks for supporting this project. I just confirmed that the current documentation includes the `commands` object so this change is indeed necessary. Since this is your work, would you like to submit a pull request? Otherwise I'll take care of this bug tonight.

Greetings
Yannik

**Comment by dominikkarall** [comment]
Hi Yannik,
I created a pull request for the issue: #5 
Regards
Dominik
