### ISSUE TITLE
Problems with Actions on Google Konsole (Connection?)

### ISSUE THREAD

**Issue by StefanRu1** [yanniks/ghome-fhem#7]
Hi,

sorry for having again a question.
Ghome is running and detecting devices in my FHEM room.
For Actions on Google, I did everything as explained. 
(Setup account linking, uploading action.json, ...)

If i open the Test console in Actions on Google and try something i get
{
  "response": "We're sorry, but something went wrong. Please try again.",
  "expectUserResponse": false,
  "conversationToken": "",
  "audioResponse": "",
  "clientError": 0,
  "is3pResponse": false
}

And i even do not see a request from Google in my Ghome on raspberry console.
But a request from Browser like:
https://mynoipadress:3000/
is accepted and answered with "Cannot GET / " in Browser and with "GET / 404 33.483 ms - 139" In raspberry console.

Do you have i Idea what i am missing?
Is it possible that i need a SSL certificate from Let's Encrypt and install it somehow on my raspberry?
What do you think?

I continued with the documentation and have choosen my test Fhem application in the Google Assistant Smart Home section and i get a login screen I entered my user and password from config.json and got on smartphone and in the console:
/login  { redirect: '',
  client_id: 'stefan',
  redirect_uri: 'https%3A%2F%2Foauth-redirect.googleusercontent.com%2Fr%2Ffhem-f0380',
  state: 'CrACQU1uRHRTRWtudE1DeDBTY3lTYWx0eko3ZmZCRmpQNTItSzhqTFFwXzlOdHJUbG5GRE9oUGQyRXFJUHhBZkRhUktNdFlfc3JCWFpfakJCZHBKalpVTjR0YXJxX0hxWG1HLTRSdjJxS1VNaGFNU3BmODY3RHRkS2pnME1JMjRXZjBpYmZqQ1ZURmtIaVhxdFp2dXpoNlFmMXZDUVZNUGg1SU16ZUlqaFBfdDJSa0FuR01ycTZmeXVvdHVod0ZxOEpscDlNaXV0NGl2am9ianV2WlRNU1dlWTNFc3VJcHllT2NoRHRteDVrVmlHc2o4RXZ3RnFBUlNtWjQ2UnhXbWRrNU9icWtFU2R5MzlSdmwzWllpSEhTYlV2ZEZYYWpNWElTclVRaG5qeWQzUVlVZFA2dRIcYXNzaXN0YW50LWhhbmRvZmY6Ly9jb21wbGV0ZSI5aHR0cHM6Ly9vYXV0aC1yZWRpcmVjdC5nb29nbGV1c2VyY29udGVudC5jb20vci9maGVtLWYwMzgwKhZydW5nZS5zdGVmYW5AZ21haWwuY29tMg5maGVtLWYwMzgwX2Rldg',
  username: 'stefan',
  password: 'mypassword' }
getUser stefan
not a user undefined
not a user false
Error: No default engine was specified and no extension was provided.
    at new View (/opt/fhem/ghome-fhem/node_modules/express/lib/view.js:61:11)
    at Function.render (/opt/fhem/ghome-fhem/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/opt/fhem/ghome-fhem/node_modules/express/lib/response.js:1008:7)
    at login (/opt/fhem/ghome-fhem/lib/auth-provider.js:389:16)
    at /opt/fhem/ghome-fhem/lib/auth-provider.js:210:20
    at Layer.handle [as handle_request] (/opt/fhem/ghome-fhem/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/fhem/ghome-fhem/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/fhem/ghome-fhem/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/fhem/ghome-fhem/node_modules/express/lib/router/layer.js:95:5)
    at /opt/fhem/ghome-fhem/node_modules/express/lib/router/index.js:281:22
POST /login 500 9.920 ms - 1182

Thanks again,
Stefan

**Comment by fhempy** [comment]
Hi,
you definitely need a valid official certificate, otherwise it's not working. I created one from LetsEncrypt which worked for me.
Nevertheless, I'm not sure if that is the root cause in your case, as the error shows something different as well:
getUser stefan
not a user undefined
not a user false
Error: No default engine was specified and no extension was provided.

Regards,
Dominik

**Comment by StefanRu1** [comment]
Ok,
I will install a SSL certificate. 
Can you tell me which user i have to insert in the APP when connecting to my host on port 3000?
Is it the user from json.conf or the google user?

Thank you.

**Comment by yanniks** [comment]
You'll have to use the username and password from `config.json` inside the Google Home / Google Assistant app.

**Comment by StefanRu1** [comment]
Thanks,

i installed certificate from lets encrypt and it is working in browser. A valid certificate is displayed.
When select my test app in google assistant on smartphone i am forwarded to a login screen where i insert my login data from json.conf.
But i still get the below error.

Do you have an idea what this might mean? What am i missing?


GET /oauth?response_type=code&client_id=stefan&redirect_uri=https://oauth-redirect.googleusercontent.com/r/fhem-api-84e41&state=CsACQU1uRHRTSFRCVHRfMHlpWFIzek9Pa3E5OUpTZmU3N2h3WnNDQk9sSHFMWlZVVExyNU9jYXhmYkJwLTFBTEw4UkhwbkRBOXVCeXRlRlYyUmE4TnoxWnZvb2FGeXNpYnljOEs4a2xxY1lvMFNrQTZyMUx1S2FPb1ZWWXphTFJOMjRtc2l2MzRMZlNISVZERG1DaWxHM0UyZlh1SmNjRHNHYzhKdUVSWjNsMHNPSmRuYV8tTy1wZG1Kdk96TnJVZkZMeDJ3UXNReHFXLUFUTDZmUnBsV1FmOXRUS2F6cW1UYmFNNWJOOUktSU1EU1hfeE05UU1oU3liekJKc25MY2ZKNURQdFdRdU1ETDhUYWJRMERoX2tkQldBa2ZEWU5BNFpHTWtpUjJ4M01IekVDUnZfRElSck1aeFROaU90VTFBX2USHGFzc2lzdGFudC1oYW5kb2ZmOi8vY29tcGxldGUiPWh0dHBzOi8vb2F1dGgtcmVkaXJlY3QuZ29vZ2xldXNlcmNvbnRlbnQuY29tL3IvZmhlbS1hcGktODRlNDEqFnJ1bmdlLnN0ZWZhbkBnbWFpbC5jb20yEmZoZW0tYXBpLTg0ZTQxX2Rldg 302 86.235 ms - 1558
GET /login?client_id=stefan&redirect_uri=https%3A%2F%2Foauth-redirect.googleusercontent.com%2Fr%2Ffhem-api-84e41&redirect=/oauth&state=CsACQU1uRHRTSFRCVHRfMHlpWFIzek9Pa3E5OUpTZmU3N2h3WnNDQk9sSHFMWlZVVExyNU9jYXhmYkJwLTFBTEw4UkhwbkRBOXVCeXRlRlYyUmE4TnoxWnZvb2FGeXNpYnljOEs4a2xxY1lvMFNrQTZyMUx1S2FPb1ZWWXphTFJOMjRtc2l2MzRMZlNISVZERG1DaWxHM0UyZlh1SmNjRHNHYzhKdUVSWjNsMHNPSmRuYV8tTy1wZG1Kdk96TnJVZkZMeDJ3UXNReHFXLUFUTDZmUnBsV1FmOXRUS2F6cW1UYmFNNWJOOUktSU1EU1hfeE05UU1oU3liekJKc25MY2ZKNURQdFdRdU1ETDhUYWJRMERoX2tkQldBa2ZEWU5BNFpHTWtpUjJ4M01IekVDUnZfRElSck1aeFROaU90VTFBX2USHGFzc2lzdGFudC1oYW5kb2ZmOi8vY29tcGxldGUiPWh0dHBzOi8vb2F1dGgtcmVkaXJlY3QuZ29vZ2xldXNlcmNvbnRlbnQuY29tL3IvZmhlbS1hcGktODRlNDEqFnJ1bmdlLnN0ZWZhbkBnbWFpbC5jb20yEmZoZW0tYXBpLTg0ZTQxX2Rldg 200 43.367 ms - 9126
GET /bower_components/polymer/polymer.html 404 15.142 ms - 176
GET /bower_components/app-layout/app-header/app-header.html 404 10.693 ms - 193
GET /bower_components/app-layout/app-scroll-effects/app-scroll-effects.html 404 3.484 ms - 209
GET /bower_components/app-layout/app-toolbar/app-toolbar.html 404 16.099 ms - 195
GET /bower_components/iron-icon/iron-icon.html 404 14.426 ms - 180
GET /bower_components/iron-icons/iron-icons.html 404 12.888 ms - 182
GET /bower_components/iron-icons/social-icons.html 404 10.147 ms - 184
GET /bower_components/iron-icons/communication-icons.html 404 6.474 ms - 191
GET /bower_components/iron-list/iron-list.html 404 5.176 ms - 180
GET /bower_components/paper-dialog/paper-dialog.html 404 2.232 ms - 186
GET /bower_components/paper-input/paper-input.html 404 7.954 ms - 184
GET /bower_components/paper-button/paper-button.html 404 6.659 ms - 186
GET /bower_components/paper-icon-button/paper-icon-button.html 404 5.398 ms - 196
GET /bower_components/paper-toast/paper-toast.html 404 6.318 ms - 184
GET /images/assistant-small.png 404 5.179 ms - 165
GET /service-worker.js 404 1.907 ms - 156
GET /images/favicon.ico 404 1.994 ms - 157
GET /images/manifest/icon-192x192.png 404 3.045 ms - 171
GET /images/manifest/icon-144x144.png 404 1.856 ms - 171
GET /images/manifest/icon-96x96.png 404 1.938 ms - 169
GET /images/manifest/icon-72x72.png 404 3.477 ms - 169
GET /images/manifest/icon-48x48.png 404 3.435 ms - 169
/login  { redirect: '',
  client_id: 'stefan',
  redirect_uri: 'https%3A%2F%2Foauth-redirect.googleusercontent.com%2Fr%2Ffhem-api-84e41',
  state: 'CsACQU1uRHRTSFRCVHRfMHlpWFIzek9Pa3E5OUpTZmU3N2h3WnNDQk9sSHFMWlZVVExyNU9jYXhmYkJwLTFBTEw4UkhwbkRBOXVCeXRlRlYyUmE4TnoxWnZvb2FGeXNpYnljOEs4a2xxY1lvMFNrQTZyMUx1S2FPb1ZWWXphTFJOMjRtc2l2MzRMZlNISVZERG1DaWxHM0UyZlh1SmNjRHNHYzhKdUVSWjNsMHNPSmRuYV8tTy1wZG1Kdk96TnJVZkZMeDJ3UXNReHFXLUFUTDZmUnBsV1FmOXRUS2F6cW1UYmFNNWJOOUktSU1EU1hfeE05UU1oU3liekJKc25MY2ZKNURQdFdRdU1ETDhUYWJRMERoX2tkQldBa2ZEWU5BNFpHTWtpUjJ4M01IekVDUnZfRElSck1aeFROaU90VTFBX2USHGFzc2lzdGFudC1oYW5kb2ZmOi8vY29tcGxldGUiPWh0dHBzOi8vb2F1dGgtcmVkaXJlY3QuZ29vZ2xldXNlcmNvbnRlbnQuY29tL3IvZmhlbS1hcGktODRlNDEqFnJ1bmdlLnN0ZWZhbkBnbWFpbC5jb20yEmZoZW0tYXBpLTg0ZTQxX2Rldg',
  username: 'stefan',
  password: 'xxxxxx' }
getUser stefan
not a user undefined
not a user false
Error: No default engine was specified and no extension was provided.
    at new View (/opt/fhem/ghome-fhem/node_modules/express/lib/view.js:61:11)
    at Function.render (/opt/fhem/ghome-fhem/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/opt/fhem/ghome-fhem/node_modules/express/lib/response.js:1008:7)
    at login (/opt/fhem/ghome-fhem/lib/auth-provider.js:389:16)
    at /opt/fhem/ghome-fhem/lib/auth-provider.js:210:20
    at Layer.handle [as handle_request] (/opt/fhem/ghome-fhem/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/fhem/ghome-fhem/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/fhem/ghome-fhem/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/fhem/ghome-fhem/node_modules/express/lib/router/layer.js:95:5)
    at /opt/fhem/ghome-fhem/node_modules/express/lib/router/index.js:281:22
POST /login 500 130.498 ms - 1182
GET /favicon.ico 404 3.512 ms - 150

**Comment by StefanRu1** [comment]
Ok i solved it.
This error means your login is not correct:
Error: No default engine was specified and no extension was provided.

You have to provide in the ghome app on smartphone when linking the:
"oauthUsers": {
			"myloginusername": {
				"password": "myloginpassword",
				"authtoken": "sometoken"
			}
		}

So myloginusername and myloginpassword must be provided.

Thanks,
Stefan
